### PR TITLE
Combine all ut99 bonus pack PKGBUILDs + fix conflicting files

### PR DESCRIPTION
**Pull request by XenGi**
Merge all ut99 bonus packs PKGBUILDs into one coming from the same source zip file from the internet archive.

### CODE REVIEW

**Comment by XenGi** [comment]
There's just one error left to fix:
```
error: failed to commit transaction (conflicting files)
unrealtournament-bonuspack1: /opt/ut/System/epiccustommodels.u exists in filesystem (owned by unrealtournament)
unrealtournament-bonuspack1: /opt/ut/System/multimesh.u exists in filesystem (owned by unrealtournament)
unrealtournament-bonuspack1: /opt/ut/System/relics.u exists in filesystem (owned by unrealtournament)
```
Seems like the first bonus pack overwrites these original files.

How should we move forward with that?

**Comment by XenGi** [comment]
I fixed the conflicting files issue by backing them up before and restoring them when the bonus pack is removed.

**Comment by XenGi** [comment]
@M0Rf30 ping ;)

**Comment by XenGi** [comment]
Thx for merging! just ping me if you need any help putting it into AUR.

**Comment by M0Rf30** [comment]
> Thx for merging! just ping me if you need any help putting it into AUR.

Hi I made you co-maintainer. The fact is that if I try to push the new package, it will conflict with already present names. I asked for merging of already present definitions.

https://aur.archlinux.org/packages/unrealtournament-bonuspacks

**Comment by XenGi** [comment]
Cool thx!
You could try deleting the old ones first.

**Comment by M0Rf30** [comment]
> Cool thx! You could try deleting the old ones first.

Finally done. all my requests are approved and I restored the sane pkgname on AUR

**Pull request merged**
